CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	active INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stories (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	headline TEXT NOT NULL,
	byline TEXT NOT NULL,
	article TEXT NOT NULL,
	FOREIGN KEY(byline) REFERENCES users(id)
);

INSERT INTO stories VALUES (NULL, "Ford to City: Drop Dead", "Newsman in 1973?", "Blah!");
